    
---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/spandanatv/ci-concourse-caching-sample.git
    branch: master
- name: deploy-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tspandana43@gmail.com
    password: Vedams@123
    organization: immerse_test
    space: development
    skip_cert_check: true
jobs:
- name: Build
  public: false
  plan:
    - get: repo
      trigger: true
    - task: Build Code
      file: repo/ci/build.yml
    - put: deploy-cf
      params:
        manifest: repo/manifest.yml
